# Display
MAX_VIRTUAL_DISPLAY_DIMENSION := 1

NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
USE_OPENGL_RENDERER := true
